name: LoginPlugin
version: '${project.version}'
main: me.lphix.loginplugin.LoginPlugin
api-version: 1.18
depend:
  - EssentialsL
commands:
  login:
    description: Logs in
    usage: /<command>
  logout:
    description: Logs out
    usage: /<command>
  register:
    description: Registers an account
    usage: /<command>
  loginadmin:
    description: Admin commands
    usage: /<command> Only for admins.
